#ifndef VMEM_CONFIG_H
#define VMEM_CONFIG_H

#include <vmem/vmem.h>
extern vmem_t vmem_config;

#define VMEM_CONF_CAPTURE_PARAM 0x00
#define VMEM_CONF_CAMERA_ID_PARAM 0x08
#define VMEM_CONF_CAMERA_TYPE_PARAM 0x0f
#define VMEM_CONF_EXPOSURE_PARAM 0x18
#define VMEM_CONF_ISO_PARAM 0x38
#define VMEM_CONF_NUM_IMAGES_PARAM 0x78
#define VMEM_CONF_INTERVAL_PARAM 0x98
#define VMEM_CONF_OBID_PARAM 0xb8
#define VMEM_CONF_ERROR_PARAM 0xd8

#endif /* VMEM_CONFIG_H */
