// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_metadata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_metadata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_metadata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_metadata_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_metadata_2eproto;
class Metadata;
struct MetadataDefaultTypeInternal;
extern MetadataDefaultTypeInternal _Metadata_default_instance_;
class MetadataItem;
struct MetadataItemDefaultTypeInternal;
extern MetadataItemDefaultTypeInternal _MetadataItem_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Metadata* Arena::CreateMaybeMessage<::Metadata>(Arena*);
template<> ::MetadataItem* Arena::CreateMaybeMessage<::MetadataItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MetadataItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MetadataItem) */ {
 public:
  inline MetadataItem() : MetadataItem(nullptr) {}
  ~MetadataItem() override;
  explicit constexpr MetadataItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MetadataItem(const MetadataItem& from);
  MetadataItem(MetadataItem&& from) noexcept
    : MetadataItem() {
    *this = ::std::move(from);
  }

  inline MetadataItem& operator=(const MetadataItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetadataItem& operator=(MetadataItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetadataItem& default_instance() {
    return *internal_default_instance();
  }
  enum ValueCase {
    kBoolValue = 2,
    kIntValue = 3,
    kFloatValue = 4,
    kStringValue = 5,
    VALUE_NOT_SET = 0,
  };

  static inline const MetadataItem* internal_default_instance() {
    return reinterpret_cast<const MetadataItem*>(
               &_MetadataItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MetadataItem& a, MetadataItem& b) {
    a.Swap(&b);
  }
  inline void Swap(MetadataItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetadataItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetadataItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MetadataItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MetadataItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const MetadataItem& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetadataItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MetadataItem";
  }
  protected:
  explicit MetadataItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kBoolValueFieldNumber = 2,
    kIntValueFieldNumber = 3,
    kFloatValueFieldNumber = 4,
    kStringValueFieldNumber = 5,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // bool bool_value = 2;
  bool has_bool_value() const;
  private:
  bool _internal_has_bool_value() const;
  public:
  void clear_bool_value();
  bool bool_value() const;
  void set_bool_value(bool value);
  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);
  public:

  // int32 int_value = 3;
  bool has_int_value() const;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  int32_t int_value() const;
  void set_int_value(int32_t value);
  private:
  int32_t _internal_int_value() const;
  void _internal_set_int_value(int32_t value);
  public:

  // float float_value = 4;
  bool has_float_value() const;
  private:
  bool _internal_has_float_value() const;
  public:
  void clear_float_value();
  float float_value() const;
  void set_float_value(float value);
  private:
  float _internal_float_value() const;
  void _internal_set_float_value(float value);
  public:

  // string string_value = 5;
  bool has_string_value() const;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_value();
  PROTOBUF_NODISCARD std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:MetadataItem)
 private:
  class _Internal;
  void set_has_bool_value();
  void set_has_int_value();
  void set_has_float_value();
  void set_has_string_value();

  inline bool has_value() const;
  inline void clear_has_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  union ValueUnion {
    constexpr ValueUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    bool bool_value_;
    int32_t int_value_;
    float float_value_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
  } value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[1];

  friend struct ::TableStruct_metadata_2eproto;
};
// -------------------------------------------------------------------

class Metadata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Metadata) */ {
 public:
  inline Metadata() : Metadata(nullptr) {}
  ~Metadata() override;
  explicit constexpr Metadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Metadata(const Metadata& from);
  Metadata(Metadata&& from) noexcept
    : Metadata() {
    *this = ::std::move(from);
  }

  inline Metadata& operator=(const Metadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline Metadata& operator=(Metadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Metadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const Metadata* internal_default_instance() {
    return reinterpret_cast<const Metadata*>(
               &_Metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Metadata& a, Metadata& b) {
    a.Swap(&b);
  }
  inline void Swap(Metadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Metadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Metadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Metadata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Metadata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Metadata& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Metadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Metadata";
  }
  protected:
  explicit Metadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 9,
    kCameraFieldNumber = 8,
    kSizeFieldNumber = 1,
    kHeightFieldNumber = 2,
    kWidthFieldNumber = 3,
    kChannelsFieldNumber = 4,
    kTimestampFieldNumber = 5,
    kBitsPixelFieldNumber = 6,
    kObidFieldNumber = 7,
  };
  // repeated .MetadataItem items = 9;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::MetadataItem* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MetadataItem >*
      mutable_items();
  private:
  const ::MetadataItem& _internal_items(int index) const;
  ::MetadataItem* _internal_add_items();
  public:
  const ::MetadataItem& items(int index) const;
  ::MetadataItem* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MetadataItem >&
      items() const;

  // string camera = 8;
  void clear_camera();
  const std::string& camera() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camera(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camera();
  PROTOBUF_NODISCARD std::string* release_camera();
  void set_allocated_camera(std::string* camera);
  private:
  const std::string& _internal_camera() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camera(const std::string& value);
  std::string* _internal_mutable_camera();
  public:

  // int32 size = 1;
  void clear_size();
  int32_t size() const;
  void set_size(int32_t value);
  private:
  int32_t _internal_size() const;
  void _internal_set_size(int32_t value);
  public:

  // int32 height = 2;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // int32 width = 3;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 channels = 4;
  void clear_channels();
  int32_t channels() const;
  void set_channels(int32_t value);
  private:
  int32_t _internal_channels() const;
  void _internal_set_channels(int32_t value);
  public:

  // int32 timestamp = 5;
  void clear_timestamp();
  int32_t timestamp() const;
  void set_timestamp(int32_t value);
  private:
  int32_t _internal_timestamp() const;
  void _internal_set_timestamp(int32_t value);
  public:

  // int32 bits_pixel = 6;
  void clear_bits_pixel();
  int32_t bits_pixel() const;
  void set_bits_pixel(int32_t value);
  private:
  int32_t _internal_bits_pixel() const;
  void _internal_set_bits_pixel(int32_t value);
  public:

  // int32 obid = 7;
  void clear_obid();
  int32_t obid() const;
  void set_obid(int32_t value);
  private:
  int32_t _internal_obid() const;
  void _internal_set_obid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Metadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MetadataItem > items_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camera_;
  int32_t size_;
  int32_t height_;
  int32_t width_;
  int32_t channels_;
  int32_t timestamp_;
  int32_t bits_pixel_;
  int32_t obid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_metadata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MetadataItem

// string key = 1;
inline void MetadataItem::clear_key() {
  key_.ClearToEmpty();
}
inline const std::string& MetadataItem::key() const {
  // @@protoc_insertion_point(field_get:MetadataItem.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MetadataItem::set_key(ArgT0&& arg0, ArgT... args) {
 
 key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MetadataItem.key)
}
inline std::string* MetadataItem::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:MetadataItem.key)
  return _s;
}
inline const std::string& MetadataItem::_internal_key() const {
  return key_.Get();
}
inline void MetadataItem::_internal_set_key(const std::string& value) {
  
  key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MetadataItem::_internal_mutable_key() {
  
  return key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MetadataItem::release_key() {
  // @@protoc_insertion_point(field_release:MetadataItem.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MetadataItem::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (key_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MetadataItem.key)
}

// bool bool_value = 2;
inline bool MetadataItem::_internal_has_bool_value() const {
  return value_case() == kBoolValue;
}
inline bool MetadataItem::has_bool_value() const {
  return _internal_has_bool_value();
}
inline void MetadataItem::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void MetadataItem::clear_bool_value() {
  if (_internal_has_bool_value()) {
    value_.bool_value_ = false;
    clear_has_value();
  }
}
inline bool MetadataItem::_internal_bool_value() const {
  if (_internal_has_bool_value()) {
    return value_.bool_value_;
  }
  return false;
}
inline void MetadataItem::_internal_set_bool_value(bool value) {
  if (!_internal_has_bool_value()) {
    clear_value();
    set_has_bool_value();
  }
  value_.bool_value_ = value;
}
inline bool MetadataItem::bool_value() const {
  // @@protoc_insertion_point(field_get:MetadataItem.bool_value)
  return _internal_bool_value();
}
inline void MetadataItem::set_bool_value(bool value) {
  _internal_set_bool_value(value);
  // @@protoc_insertion_point(field_set:MetadataItem.bool_value)
}

// int32 int_value = 3;
inline bool MetadataItem::_internal_has_int_value() const {
  return value_case() == kIntValue;
}
inline bool MetadataItem::has_int_value() const {
  return _internal_has_int_value();
}
inline void MetadataItem::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
inline void MetadataItem::clear_int_value() {
  if (_internal_has_int_value()) {
    value_.int_value_ = 0;
    clear_has_value();
  }
}
inline int32_t MetadataItem::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return value_.int_value_;
  }
  return 0;
}
inline void MetadataItem::_internal_set_int_value(int32_t value) {
  if (!_internal_has_int_value()) {
    clear_value();
    set_has_int_value();
  }
  value_.int_value_ = value;
}
inline int32_t MetadataItem::int_value() const {
  // @@protoc_insertion_point(field_get:MetadataItem.int_value)
  return _internal_int_value();
}
inline void MetadataItem::set_int_value(int32_t value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:MetadataItem.int_value)
}

// float float_value = 4;
inline bool MetadataItem::_internal_has_float_value() const {
  return value_case() == kFloatValue;
}
inline bool MetadataItem::has_float_value() const {
  return _internal_has_float_value();
}
inline void MetadataItem::set_has_float_value() {
  _oneof_case_[0] = kFloatValue;
}
inline void MetadataItem::clear_float_value() {
  if (_internal_has_float_value()) {
    value_.float_value_ = 0;
    clear_has_value();
  }
}
inline float MetadataItem::_internal_float_value() const {
  if (_internal_has_float_value()) {
    return value_.float_value_;
  }
  return 0;
}
inline void MetadataItem::_internal_set_float_value(float value) {
  if (!_internal_has_float_value()) {
    clear_value();
    set_has_float_value();
  }
  value_.float_value_ = value;
}
inline float MetadataItem::float_value() const {
  // @@protoc_insertion_point(field_get:MetadataItem.float_value)
  return _internal_float_value();
}
inline void MetadataItem::set_float_value(float value) {
  _internal_set_float_value(value);
  // @@protoc_insertion_point(field_set:MetadataItem.float_value)
}

// string string_value = 5;
inline bool MetadataItem::_internal_has_string_value() const {
  return value_case() == kStringValue;
}
inline bool MetadataItem::has_string_value() const {
  return _internal_has_string_value();
}
inline void MetadataItem::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void MetadataItem::clear_string_value() {
  if (_internal_has_string_value()) {
    value_.string_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
    clear_has_value();
  }
}
inline const std::string& MetadataItem::string_value() const {
  // @@protoc_insertion_point(field_get:MetadataItem.string_value)
  return _internal_string_value();
}
template <typename ArgT0, typename... ArgT>
inline void MetadataItem::set_string_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MetadataItem.string_value)
}
inline std::string* MetadataItem::mutable_string_value() {
  std::string* _s = _internal_mutable_string_value();
  // @@protoc_insertion_point(field_mutable:MetadataItem.string_value)
  return _s;
}
inline const std::string& MetadataItem::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return value_.string_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void MetadataItem::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MetadataItem::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return value_.string_value_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MetadataItem::release_string_value() {
  // @@protoc_insertion_point(field_release:MetadataItem.string_value)
  if (_internal_has_string_value()) {
    clear_has_value();
    return value_.string_value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
  } else {
    return nullptr;
  }
}
inline void MetadataItem::set_allocated_string_value(std::string* string_value) {
  if (has_value()) {
    clear_value();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    value_.string_value_.UnsafeSetDefault(string_value);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArenaForAllocation();
    if (arena != nullptr) {
      arena->Own(string_value);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:MetadataItem.string_value)
}

inline bool MetadataItem::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void MetadataItem::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline MetadataItem::ValueCase MetadataItem::value_case() const {
  return MetadataItem::ValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Metadata

// int32 size = 1;
inline void Metadata::clear_size() {
  size_ = 0;
}
inline int32_t Metadata::_internal_size() const {
  return size_;
}
inline int32_t Metadata::size() const {
  // @@protoc_insertion_point(field_get:Metadata.size)
  return _internal_size();
}
inline void Metadata::_internal_set_size(int32_t value) {
  
  size_ = value;
}
inline void Metadata::set_size(int32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:Metadata.size)
}

// int32 height = 2;
inline void Metadata::clear_height() {
  height_ = 0;
}
inline int32_t Metadata::_internal_height() const {
  return height_;
}
inline int32_t Metadata::height() const {
  // @@protoc_insertion_point(field_get:Metadata.height)
  return _internal_height();
}
inline void Metadata::_internal_set_height(int32_t value) {
  
  height_ = value;
}
inline void Metadata::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:Metadata.height)
}

// int32 width = 3;
inline void Metadata::clear_width() {
  width_ = 0;
}
inline int32_t Metadata::_internal_width() const {
  return width_;
}
inline int32_t Metadata::width() const {
  // @@protoc_insertion_point(field_get:Metadata.width)
  return _internal_width();
}
inline void Metadata::_internal_set_width(int32_t value) {
  
  width_ = value;
}
inline void Metadata::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:Metadata.width)
}

// int32 channels = 4;
inline void Metadata::clear_channels() {
  channels_ = 0;
}
inline int32_t Metadata::_internal_channels() const {
  return channels_;
}
inline int32_t Metadata::channels() const {
  // @@protoc_insertion_point(field_get:Metadata.channels)
  return _internal_channels();
}
inline void Metadata::_internal_set_channels(int32_t value) {
  
  channels_ = value;
}
inline void Metadata::set_channels(int32_t value) {
  _internal_set_channels(value);
  // @@protoc_insertion_point(field_set:Metadata.channels)
}

// int32 timestamp = 5;
inline void Metadata::clear_timestamp() {
  timestamp_ = 0;
}
inline int32_t Metadata::_internal_timestamp() const {
  return timestamp_;
}
inline int32_t Metadata::timestamp() const {
  // @@protoc_insertion_point(field_get:Metadata.timestamp)
  return _internal_timestamp();
}
inline void Metadata::_internal_set_timestamp(int32_t value) {
  
  timestamp_ = value;
}
inline void Metadata::set_timestamp(int32_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:Metadata.timestamp)
}

// int32 bits_pixel = 6;
inline void Metadata::clear_bits_pixel() {
  bits_pixel_ = 0;
}
inline int32_t Metadata::_internal_bits_pixel() const {
  return bits_pixel_;
}
inline int32_t Metadata::bits_pixel() const {
  // @@protoc_insertion_point(field_get:Metadata.bits_pixel)
  return _internal_bits_pixel();
}
inline void Metadata::_internal_set_bits_pixel(int32_t value) {
  
  bits_pixel_ = value;
}
inline void Metadata::set_bits_pixel(int32_t value) {
  _internal_set_bits_pixel(value);
  // @@protoc_insertion_point(field_set:Metadata.bits_pixel)
}

// int32 obid = 7;
inline void Metadata::clear_obid() {
  obid_ = 0;
}
inline int32_t Metadata::_internal_obid() const {
  return obid_;
}
inline int32_t Metadata::obid() const {
  // @@protoc_insertion_point(field_get:Metadata.obid)
  return _internal_obid();
}
inline void Metadata::_internal_set_obid(int32_t value) {
  
  obid_ = value;
}
inline void Metadata::set_obid(int32_t value) {
  _internal_set_obid(value);
  // @@protoc_insertion_point(field_set:Metadata.obid)
}

// string camera = 8;
inline void Metadata::clear_camera() {
  camera_.ClearToEmpty();
}
inline const std::string& Metadata::camera() const {
  // @@protoc_insertion_point(field_get:Metadata.camera)
  return _internal_camera();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Metadata::set_camera(ArgT0&& arg0, ArgT... args) {
 
 camera_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Metadata.camera)
}
inline std::string* Metadata::mutable_camera() {
  std::string* _s = _internal_mutable_camera();
  // @@protoc_insertion_point(field_mutable:Metadata.camera)
  return _s;
}
inline const std::string& Metadata::_internal_camera() const {
  return camera_.Get();
}
inline void Metadata::_internal_set_camera(const std::string& value) {
  
  camera_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Metadata::_internal_mutable_camera() {
  
  return camera_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Metadata::release_camera() {
  // @@protoc_insertion_point(field_release:Metadata.camera)
  return camera_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Metadata::set_allocated_camera(std::string* camera) {
  if (camera != nullptr) {
    
  } else {
    
  }
  camera_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), camera,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (camera_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    camera_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Metadata.camera)
}

// repeated .MetadataItem items = 9;
inline int Metadata::_internal_items_size() const {
  return items_.size();
}
inline int Metadata::items_size() const {
  return _internal_items_size();
}
inline void Metadata::clear_items() {
  items_.Clear();
}
inline ::MetadataItem* Metadata::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:Metadata.items)
  return items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MetadataItem >*
Metadata::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:Metadata.items)
  return &items_;
}
inline const ::MetadataItem& Metadata::_internal_items(int index) const {
  return items_.Get(index);
}
inline const ::MetadataItem& Metadata::items(int index) const {
  // @@protoc_insertion_point(field_get:Metadata.items)
  return _internal_items(index);
}
inline ::MetadataItem* Metadata::_internal_add_items() {
  return items_.Add();
}
inline ::MetadataItem* Metadata::add_items() {
  ::MetadataItem* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:Metadata.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MetadataItem >&
Metadata::items() const {
  // @@protoc_insertion_point(field_list:Metadata.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_metadata_2eproto
